version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "base1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vqcsjaogndqt"
s3_prefix = "base1"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
